---
name: mxlims
channels:
  - conda-forge
dependencies:
  - python=3.10,<3.12
  - pip
  - poetry ==2.1.3
  - pip:
      - ruff
      - yamllint
      - packaging
      - json-schema-for-humans
      - jsonschema
      - ruamel.yaml==0.17.21
      - pydantic==2.8.2
      - datamodel-code-generator==0.54.0
      - --editable /home/rhfogh/pycharm/mxlims_data_model
